const baseURL = process.env.REACT_APP_API_URL;

export const urlNews = `${baseURL}/api/news`;
export const urlMahber = `${baseURL}/api/mahber`;
export const urlusers = `${baseURL}/api/users`;
export const urlVideos = `${baseURL}/api/videos`;
export const urlMember = `${baseURL}/api/member`;
export const urlMatch = `${baseURL}/api/matches`;
export const urlTmretExec = `${baseURL}/api/tmretexc`;
export const urlMahberExec = `${baseURL}/api/mahberexec`;
export const urlDegafi = `${baseURL}/api/degafi`;
export const urlAdvert = `${baseURL}/api/advert`;
export const urlDegafiSetting = `${baseURL}/api/degafisetting`;
export const urlDashboard = `${baseURL}/api/dashboard`;
export const urlSeason =   `${baseURL}/api/season`;
export const urlTeam = `${baseURL}/api/team`;
export const urlMatchWeek = `${baseURL}/api/matcheweeks`;
export const urlPlayer = `${baseURL}/api/players`;
export const assetUrl = baseURL;